config/routes.rb
Glossarium::Application.routes.draw do
  resources :collections do
    resources :entries
  end

  root :to => redirect("/collections")
end

app/models/collection.rb
class Collection < ActiveRecord::Base
  acts_as_taggable
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :entries
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  acts_as_taggable
  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :collection
  validates :collection, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: [:show, :edit, :update, :destroy]

  def index
    if params[:tag]
      @entries = Collection.tagged_with(params[:tag]).decorate
    else
      @entries = Collection.all.decorate
    end
  end

  def show; end

  def new
    @collection = Collection.new
  end

  def edit; end

  def create
    @collection = Collection.new(collection_params)

    respond_to do |format|
      if @collection.save
        format.html { redirect_to @collection, notice: 'Collection was successfully created.' }
        format.json { render action: 'show', status: :created, location: @collection }
      else
        format.html { render action: 'new' }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to @collection, notice: 'Collection was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @collection.destroy
    respond_to do |format|
      format.html { redirect_to entries_url }
      format.json { head :no_content }
    end
  end

  private
  def set_collection
    @collection = Collection.friendly.find(params[:id]).decorate
  end

  def collection_params
    params.require(:collection).permit(:name, :tag_list)
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_collection
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  def index
    if params[:tag]
      @entries = @collection.entries.tagged_with(params[:tag]).decorate
    else
      @entries = @collection.entries.decorate
    end
  end

  def show; end

  def new
    @entry = Entry.new(collection: @collection)
  end

  def edit; end

  def create
    @entry = Entry.new(entry_params.merge(collection: @collection))

    respond_to do |format|
      if @entry.save
        format.html { redirect_to [@collection, @entry], notice: 'Entry was successfully created.' }
        format.json { render action: 'show', status: :created, location: @entry }
      else
        format.html { render action: 'new' }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to [@collection, @entry], notice: 'Entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to collection_entries_url(@collection) }
      format.json { head :no_content }
    end
  end

  private
  def set_collection
    @collection = Collection.friendly.find(params[:collection_id]).decorate
  end

  def set_entry
    @entry = @collection.entries.friendly.find(params[:id]).decorate
  end

  def entry_params
    params.require(:entry).permit(:name, :tag_list)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/collections/_form.html.haml
= simple_form_for(@collection) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name

  .form-actions
    = f.button :submit

app/views/collections/edit.html.haml
%h1 Editing collection

= render 'form'

= link_to 'Show', @collection
\|
= link_to 'Back', collections_path

app/views/collections/index.html.haml
.row.header-row
  .right
    .button.round
      = link_to 'New Collection', new_collection_path
      %i.foundicon-plus
  %h1
    .large-8
      Listing collections

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @entries.each do |collection|
    %tr
      %td= collection.name
      %td= link_to 'Show', collection
      %td= link_to 'Edit', edit_collection_path(collection)
      %td= link_to 'Destroy', collection, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

app/views/collections/new.html.haml
%h1 New collection

= render 'form'

= link_to 'Back', collections_path

app/views/collections/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @collection.name

= link_to 'Edit', edit_collection_path(@collection)
\|
= link_to 'Back', collections_path

= render "entries/index"

app/views/entries/_form.html.haml
- url = @entry.persisted? ? edit_collection_entry_path(@collection, @entry) : collection_entries_path(@collection)
= simple_form_for(@entry, url: url) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :tag_list

  .form-actions
    = f.button :submit

app/views/entries/_index.html.haml
.row.header-row
  .right
    .button.round
      = link_to 'New Entry', new_collection_entry_path(@collection)
      %i.foundicon-plus
  = yield :index_header

%table
  %tr
    %th Name
    %th Tag List
    %th
    %th
    %th

  - @collection.entries.decorate.each do |entry|
    %tr
      %td= entry.name
      %td= entry.tag_list_links
      %td= link_to 'Show', collection_entry_path(@collection, entry)
      %td= link_to 'Edit', edit_collection_entry_path(@collection, entry)
      %td= link_to 'Destroy', collection_entry_path(@collection, entry), :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

app/views/entries/edit.html.haml
%h1 Editing entry

= render 'form'

= link_to 'Show', @entry
\|
= link_to 'Back', collection_entries_path(@collection)

app/views/entries/index.html.haml
- content_for :index_header do
  %h1
    .large-8
      Listing entries

= render "entries/index"

app/views/entries/new.html.haml
%h1 New entry

= render 'form'

= link_to 'Back', collection_entries_path(@collection)

app/views/entries/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @entry.name
%p
  %b Tags:
  = @entry.tag_list_links

= link_to 'Edit', edit_collection_entry_path(@collection, @entry)
\|
= link_to 'Back', collection_entries_path(@collection)

app/views/layouts/_footer.html.haml
%footer.row
  .large-12.columns
    %hr/
    .row
      .large-6.columns
        %p © Copyright 2013

app/views/layouts/_header_and_nav.html.haml
%nav.top-bar
  %ul.title-area
    %li.name
      %h1
        =link_to("glossārium", root_path)
    %li.toggle-topbar.menu-icon
      %a{:href => "#"}
        %span
  .top-bar-section
    = render :partial => 'layouts/sections', locals: { classes: "right" }

app/views/layouts/_nav_sidebar.html.haml
/ This is source ordered to be pulled to the left on larger screens
.large-3.pull-9.columns
  %h3 Navigation
  = render :partial => 'layouts/sections', locals: { classes: "side-nav" }

  %h3 Tag Cloud
  .tag_cloud
    - tag_cloud Entry.tag_counts, %w{s m l} do |tag, css_class|
      = link_to(tag.name, tag_path(tag.name), class: css_class)

app/views/layouts/_sections.html.haml
%ul{class: classes}
  %li
    = link_to("Collections", collections_path)
  %li
    = link_to("Entries", collection_entries_path(@collection)) if @collection

app/views/layouts/application.html.haml
!!!
/ paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/
/[if lt IE 7 ] <html class="ie6" lang="en">
/[if IE 7 ] <html class="ie7" lang="en">
/[if IE 8 ] <html class="ie8" lang="en">
/ [if (gte IE 9)|!(IE)]><!
%html{:lang => "en"}
  / <![endif]
  %head
    %meta{:charset => "utf-8"}/
    / Uncomment to make IE8 render like IE7
    / <meta http-equiv="X-UA-Compatible" content="IE=7" />
    / Set the viewport width to device width for mobile
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Untitled"
    = stylesheet_link_tag    "application"
    = javascript_include_tag "vendor/custom.modernizr"
    = csrf_meta_tags
  %body
    / Header and Nav
    .main-content
      = render :partial => 'layouts/header_and_nav'
      .row
        / Main Content Section
        / This has been source ordered to come first in the markup (and on small devices) but to be to the right of the nav on larger screens
        .large-9.push-3.columns
          = yield
        = render :partial => 'layouts/nav_sidebar'
    / Footer
    = render :partial => 'layouts/footer'

  = javascript_include_tag "application"